# =========================================================================
# BASE CONFIG
# =========================================================================
spring.application.name=taxi

# i18n
spring.messages.basename=i18n/common_errors,i18n/common_messages,i18n/driver_errors,i18n/driver_messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=true

# Paging and Sorting
spring.data.web.pageable.one-indexed-parameters=true
spring.data.web.pageable.default-page-size=100
spring.data.web.pageable.max-page-size=1000

# JWT Expiration
security.token.access.expiration-minutes=30
security.token.refresh.expiration-minutes=10080

# DEFAULT ACTIVE PROFILE
spring.profiles.active=dev
