# =========================================================================
# LOCAL (dev)
# =========================================================================

# DB Access für lokale Entwicklung
spring.datasource.url=jdbc:postgresql://localhost:5432/taxi_controlling_db
spring.datasource.username=marko
spring.datasource.password=admin

# Strategie: Hibernate generiert die Tabellen automatisch
spring.jpa.hibernate.ddl-auto=update
spring.liquibase.enabled=false

# Ausführliche Logs beim Entwickeln
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

jwt.secret=qWZVj4ZMRuIZYOQv0Xury3RQ1aqxCzGrYckbGaCXwr8
#shared secret: xCvXNENDE8nyzrmyU+XJKh6B46EBzQ2iiVb4KAQyFdg=