# =========================================================================
# BASE CONFIG
# =========================================================================
spring.application.name=taxi
spring.mvc.problemdetails.enabled=true

# i18n
spring.messages.basename=i18n/errors,i18n/messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=true

# Paging and Sorting
spring.data.web.pageable.one-indexed-parameters=true
spring.data.web.pageable.default-page-size=100
spring.data.web.pageable.max-page-size=1000

# JWT
security.token.access.expiration-minutes=30
security.token.refresh.expiration-minutes=10080

# JPA
spring.jpa.open-in-view=false

# DEFAULT ACTIVE PROFILE
spring.profiles.active=dev

# Swagger Security Credentials
swagger.security.username=developer
swagger.security.password=swagger2026
