# =========================================================================
# PRODUCTION
# =========================================================================

# DB Access zieht sich die sicheren Docker-Umgebungsvariablen
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Strategie: Absolut sicher. Hibernate ffasst nichts an, Liquibase migriert!
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.enabled=true

# Logs schonen in der Produktion
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=ERROR
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

jwt.secret=${JWT_SECRET}
