# =========================================================================
# BASE CONFIG
# =========================================================================
spring.application.name=taxi
spring.mvc.problemdetails.enabled=true

# i18n
spring.messages.basename=i18n/errors,i18n/messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=true

# Paging and Sorting
spring.data.web.pageable.one-indexed-parameters=true
spring.data.web.pageable.default-page-size=100
spring.data.web.pageable.max-page-size=1000

# JWT
security.token.access.expiration-minutes=30
security.token.refresh.expiration-minutes=10080

# JPA & Datasource
spring.jpa.open-in-view=false
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

# DEFAULT ACTIVE PROFILE
spring.profiles.active=dev

# Swagger / OpenAPI Paths
springdoc.swagger-ui.path=/api/swagger-ui.html
springdoc.api-docs.path=/api/v3/api-docs

# Observability (Actuator & Prometheus)
management.server.port=8081
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# Logging Pattern (includes MDC TenantId)
logging.pattern.console=%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd'T'HH:mm:ss.SSSXXX}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} [Tenant: %X{tenantId:-SYSTEM}] %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}
