### Global Variables
@host = http://localhost:8080
@api = /api/revenues

### 0. Login (to get accessToken)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "max@mustermann.de",
  "password": "securePassword123"
}

> {%
    client.global.set("accessToken", response.body.data.accessToken);
%}


### GET ALL REVENUES
GET {{host}}{{api}}
Content-Type: application/json
Cookie: accessToken={{accessToken}}

### 1. Create Daily Percentage Share Revenue (Manual)
POST {{host}}{{api}}
Content-Type: application/json
Cookie: accessToken={{accessToken}}

{
  "driverId": 3,
  "carId": 1,
  "date": "2026-03-26",
  "kilometersDriven": 150.0,
  "kilometersFrom": 1000.0,
  "kilometersTo": 1150.0,
  "revenueType": "MANUAL_DAILY_REVENUE",
  "drivenFrom": "08:00:00",
  "drivenTo": "17:00:00",
  "revenue": 450.0
}

### 2. Create Daily WEEKLY_FIXED_RATE without SETTLEMENT Revenue
POST {{host}}{{api}}
Content-Type: application/json
Cookie: accessToken={{accessToken}}

{
  "driverId": 10,
  "carId": 1,
  "date": "2026-03-26",
  "kilometersDriven": 150.0,
  "kilometersFrom": 2000.0,
  "kilometersTo": 2150.0,
  "revenueType": "MANUAL_DAILY_REVENUE",
  "drivenFrom": "09:00:00",
  "drivenTo": "18:00:00",
  "revenue": 350.0
}

### 3. Create Daily WEEKLY_FIXED_RATE WITH SETTLEMENT Revenue
POST {{host}}{{api}}
Content-Type: application/json
Cookie: accessToken={{accessToken}}

{
  "driverId": 10,
  "carId": 1,
  "date": "2026-03-26",
  "kilometersDriven": 150.0,
  "kilometersFrom": 2150.0,
  "kilometersTo": 2300.0,
  "revenueType": "MANUAL_DAILY_REVENUE",
  "drivenFrom": "09:00:00",
  "drivenTo": "18:00:00",
  "revenue": 350.0,
  "companyRemuneration": 600.0
}

### 4. Create FLAT_RATE_TRIP (Pauschalfahrt) Revenue
# Driver 12 should have a FLAT_RATE remuneration config active (e.g. flatRateFee = 80.00)
POST {{host}}{{api}}
Content-Type: application/json
Cookie: accessToken={{accessToken}}

{
  "driverId": 12,
  "carId": 1,
  "date": "2026-03-26",
  "kilometersDriven": 80.0,
  "kilometersFrom": 3000.0,
  "kilometersTo": 3080.0,
  "revenueType": "FLAT_RATE_TRIP",
  "drivenFrom": "10:00:00",
  "drivenTo": "12:00:00",
  "tripCount": 10,
  "pricePerTrip": 100.0,
  "revenue": 1000.0
}



### 5. Create Daily Revenues Bulk (Covers multiple use cases)
POST {{host}}{{api}}/bulk
Content-Type: application/json
Cookie: accessToken={{accessToken}}

[
  {
    "driverId": 3,
    "carId": 1,
    "date": "2026-03-27",
    "kilometersDriven": 150.0,
    "kilometersFrom": 1150.0,
    "kilometersTo": 1300.0,
    "revenueType": "MANUAL_DAILY_REVENUE",
    "drivenFrom": "08:00:00",
    "drivenTo": "17:00:00",
    "revenue": 450.0
  },
  {
    "driverId": 10,
    "carId": 1,
    "date": "2026-03-27",
    "kilometersDriven": 120.0,
    "kilometersFrom": 2300.0,
    "kilometersTo": 2420.0,
    "revenueType": "MANUAL_DAILY_REVENUE",
    "drivenFrom": "09:00:00",
    "drivenTo": "18:00:00",
    "revenue": 380.0
  },
  {
    "driverId": 12,
    "carId": 1,
    "date": "2026-03-27",
    "kilometersDriven": 50.0,
    "kilometersFrom": 3080.0,
    "kilometersTo": 3130.0,
    "revenueType": "FLAT_RATE_TRIP",
    "drivenFrom": "13:00:00",
    "drivenTo": "14:30:00",
    "tripCount": 1,
    "pricePerTrip": 100.0,
    "revenue": 1000.0
  }
]
